version: "3"
services:
  web:
    image: jamj2000/web:fp-resultados
    ports:
      - "7890:80"
    restart: always
    environment:
      - PRODUCTION=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=jacaranda
      - DB_USERNAME=inma
      - DB_PASSWORD=olias
    depends_on:
      - db
  db:
    image: jamj2000/db:fp-resultados
    hostname: db
    environment:
      - MARIADB_DATABASE=jacaranda
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=inma
      - MARIADB_PASSWORD=olias
    volumes:
      - datos:/var/lib/mysql
    working_dir: /data

volumes:
    datos:
